credentials:
  usernames:
    diegopmayer:
      email: diegopmayer@gmail.com
      logged_in: False
      name: Diego Poletto Mayer
      password: Vnt794613
    suporte:
      email: diegopmayer@gmail.com
      logged_in: False
      name: Suporte
      password: supun.369
    jessica:
      email: diegopmayer@gmail.com
      logged_in: False
      name: Jéssica Analise Docs
      password: jedoc.936
    oscar:
      email: diegopmayer@gmail.com
      logged_in: False
      name: Oscara tk
      password: osctk.693
    lucas:
      email: supervisaosuportesistemas@grupounus.com.br
      logged_in: False
      name: Lucas Sistemas
      password: lcs.693
    eduardo:
      email: gerencia.sistemas@grupounus.com.br
      logged_in: False
      name: Duda Sistemas
      password: ddz.739
cookie:
  expiry_days: 1
  key: some_signature_key
  name: some_cookie_name